# Fichier d'exemple de workflow GitHub Actions pour déployer sur Vercel
# Remplacez les placeholders et ajustez selon vos besoins.

name: Deploy to Vercel

on:
  push:
    branches:
      - main # Déclenche le workflow sur un push sur la branche main

jobs:
  deploy_vercel:
    name: Deploy Next.js App to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Assurez-vous que cela correspond à votre environnement de développement

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  # Si vous souhaitez également déployer les Cloud Functions sur Firebase en même temps
  deploy_firebase_functions:
    name: Deploy Cloud Functions to Firebase
    runs-on: ubuntu-latest
    needs: deploy_vercel # S'exécute après le déploiement sur Vercel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Function Dependencies
        run: npm --prefix functions install

      - name: Deploy to Firebase Functions
        run: |
          firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project "${{ secrets.FIREBASE_PROJECT_ID }}" --non-interactive
